import { LessonModel } from "../../../core/models/lesson-model";

export const LESSONS_MOCK: LessonModel[] = [
  {
    id: 1,
    theme: 'Borges y el fantástico',
    subject: 'Lengua',
    course: '3ro A',
    duration: '80 min',
    rationale: 'Marco teórico del género fantástico',
    objectives: 'Reconocer rasgos',
    activities: 'Lectura guiada',
    resources: '',
    assessment: '',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'draft',
  },
  {
    id: 2,
    theme: 'La gauchesca',
    subject: 'Literatura argentina',
    course: '6to A',
    duration: '80 min',
    rationale: 'Marco teórico de la literatura gauchesca',
    objectives: 'Reconocer rasgos y autores',
    activities: 'Lectura guiada con análisis de fragmentos',
    resources: '',
    assessment: '',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'draft',
  },
  {
    id: 3,
    theme: 'Coherencia y cohesión',
    subject: 'Lengua',
    course: '4to A',
    duration: '80 min',
    rationale: 'Marco teórico de la coherencia y cohesión textual',
    objectives: 'Reconocer y aplicar recursos de coherencia y cohesión',
    activities: 'Análisis de textos y producción escrita',
    resources: '',
    assessment: '',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'draft',
  },
];